package alice.tuprologx.runtime.corba;


/**
* org/alice/tuprologx/runtime/corba/SolveInfo.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from org/alice/tuprologx/runtime/corba/Prolog.idl
* venerd? 28 dicembre 2001 12.37.09 GMT+01:00
*/

@SuppressWarnings("serial")
public final class SolveInfo implements org.omg.CORBA.portable.IDLEntity
{
  public boolean success;
  public String solution;
 public boolean halt;
  public int haltCode;

  public SolveInfo ()
  {
  } // ctor

  public SolveInfo (boolean _success, String _solution, boolean _halt, int _haltCode)
  {
    success = _success;
    solution = _solution;
    halt = _halt;
    haltCode = _haltCode;
  } // ctor

} // class SolveInfo
