/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufpr.gres.core.visitors.methods;

import br.ufpr.gres.core.premutation.PremutationClassInfo;
import org.objectweb.asm.Label;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import static org.objectweb.asm.Opcodes.*;

/**
 * Example of code that was generated by 1.7 compiler for try-with-resources
 * block:
 *
 * <pre>
 * <code>
 * } finally {
 *   if (closeable != null) { // IFNULL
 *     if (localThrowable2 != null) { // IFNULL
 *       try {
 *         closeable.close(); // INVOKEVIRTUAL or INVOKEINTERFACE
 *       } catch (Throwable x2) {
 *         localThrowable2.addSuppressed(x2); // INVOKEVIRTUAL
 *       }
 *     } else {
 *       closeable.close(); // INVOKEVIRTUAL or INVOKEINTERFACE
 *     }
 *   }
 * } // ATHROW
 * </code>
 * </pre>
 *
 * This class considers that only auto generated code may have such sequence
 * without any line change. Such an approach make sense only for <strong>javac
 * compiler</strong>.
 * <p>
 * <strong>Eclipse Java Compiler</strong> as well as <strong>aspectj</strong>
 * have its own opinion how to compile try-with-resources block:
 *
 * <pre>
 * <code>
 * } finally {
 *   if (throwable1 == null) { // IFNONNULL
 *     throwable1 = throwable2;
 *   } else {
 *     if (throwable1 != throwable2) { // IF_ACMPEQ
 *       throwable1.addSuppressed(throwable2); // INVOKEVIRTUAL
 *     }
 *   }
 * } // ATHROW
 * </code>
 * </pre>
 *
 * @author Artem Khvastunov &lt;contact@artspb.me&gt;
 */
public class TryWithResourcesMethodVisitor extends MethodVisitor {

    private static final List<Integer> JAVAC_CLASS_INS_SEQUENCE = Arrays
            .asList(
                    ASTORE, // store
                    // throwable
                    ALOAD,
                    IFNULL, // closeable
                    // !=
                    // null
                    ALOAD,
                    IFNULL, // localThrowable2
                    // !=
                    // null
                    ALOAD,
                    INVOKEVIRTUAL,
                    GOTO, // closeable.close()
                    ASTORE, // Throwable
                    // x2
                    ALOAD,
                    ALOAD,
                    INVOKEVIRTUAL,
                    GOTO, // localThrowable2.addSuppressed(x2)
                    ALOAD,
                    INVOKEVIRTUAL, // closeable.close()
                    ALOAD,
                    ATHROW);           // throw
    // throwable

    private static final List<Integer> JAVAC_INTERFACE_INS_SEQUENCE = Arrays
            .asList(
                    ASTORE, // store
                    // throwable
                    ALOAD,
                    IFNULL, // closeable
                    // !=
                    // null
                    ALOAD,
                    IFNULL, // localThrowable2
                    // !=
                    // null
                    ALOAD,
                    INVOKEINTERFACE,
                    GOTO, // closeable.close()
                    ASTORE, // Throwable
                    // x2
                    ALOAD,
                    ALOAD,
                    INVOKEVIRTUAL,
                    GOTO, // localThrowable2.addSuppressed(x2)
                    ALOAD,
                    INVOKEINTERFACE, // closeable.close()
                    ALOAD,
                    ATHROW);           // throw
    // throwable

    private static final List<Integer> ECJ_INS_SEQUENCE = Arrays
            .asList(
                    ASTORE, // store
                    // throwable2
                    ALOAD,
                    IFNONNULL, // if
                    // (throwable1
                    // ==
                    // null)
                    ALOAD,
                    ASTORE,
                    GOTO, // throwable1
                    // =
                    // throwable2;
                    ALOAD,
                    ALOAD,
                    IF_ACMPEQ, // if
                    // (throwable1
                    // !=
                    // throwable2)
                    // {
                    ALOAD,
                    ALOAD,
                    INVOKEVIRTUAL, // throwable1.addSuppressed(throwable2)
                    ALOAD,
                    ATHROW);           // throw
    // throwable1

    private final PremutationClassInfo context;

    private final List<Integer> opcodesStack = new ArrayList<>();
    private int currentLineNumber;

    /**
     * @param context to store detected line numbers
     */
    public TryWithResourcesMethodVisitor(final PremutationClassInfo context) {
        super(Opcodes.ASM6);
        this.context = context;
    }

    @Override
    public void visitLineNumber(int line, Label start) {
        prepareToStartTracking();
        this.currentLineNumber = line;
        super.visitLineNumber(line, start);
    }

    @Override
    public void visitVarInsn(int opcode, int var) {
        this.opcodesStack.add(opcode);
        super.visitVarInsn(opcode, var);
    }

    @Override
    public void visitJumpInsn(int opcode, Label label) {
        this.opcodesStack.add(opcode);
        super.visitJumpInsn(opcode, label);
    }

    @Override
    public void visitMethodInsn(int opcode, String owner, String name,
            String desc, boolean itf) {
        this.opcodesStack.add(opcode);
        super.visitMethodInsn(opcode, owner, name, desc, itf);
    }

    @Override
    public void visitInsn(int opcode) {
        if (opcode == Opcodes.ATHROW) {
            this.opcodesStack.add(Opcodes.ATHROW);
            finishTracking();
        }
        super.visitInsn(opcode);
    }

    private void finishTracking() {
        if (JAVAC_CLASS_INS_SEQUENCE.equals(this.opcodesStack)
                || JAVAC_INTERFACE_INS_SEQUENCE.equals(this.opcodesStack)
                || ECJ_INS_SEQUENCE.equals(this.opcodesStack)) {
            this.context.registerLineToAvoid(this.currentLineNumber);
        }
        prepareToStartTracking();
    }

    private void prepareToStartTracking() {
        if (!this.opcodesStack.isEmpty()) {
            this.opcodesStack.clear();
        }
    }
}
